version: '3.8'
services:
  apitut:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - ./app/node_modules
  myblog:
    build: ./docker-test
    container_name: react_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true