version: '3.8'
services:
  apitut:
    build: ./nodejs-docker
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./nodejs-docker:/app
      - ./app/node_modules
  myblog:
    build: ./react-docker
    container_name: react_c
    ports:
      - '3000:3000'
    volumes:
      - ./react-docker:/app
    stdin_open: true
    tty: true
